// flow-typed signature: da1f82227c3cc7b7de156fe7873b21dc
// flow-typed version: <<STUB>>/@types/react_v^15.0.29/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/react' {
  declare module.exports: any;
}
