// flow-typed signature: 4696bf60188c020ff463bfbaddb8a6a0
// flow-typed version: <<STUB>>/@types/react-hot-loader_v^3.0.1/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/react-hot-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/react-hot-loader' {
  declare module.exports: any;
}
