// flow-typed signature: d406885104b6eeb787dc971ac5505c8e
// flow-typed version: <<STUB>>/@types/react-dom_v^15.5.0/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/react-dom'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/react-dom' {
  declare module.exports: any;
}
